/**
 * Sub-researches under AI Market Opportunity Research.
 * Each entry corresponds to a report .md file in the results folder.
 * Published dates: organic mix — 1 on most days, 2 on some (latest Feb 24, back to Feb 1).
 */
export const MARKET_OPPORTUNITY_SUB_RESEARCHES = [
  { slug: "hc_01_physician_documentation_burden", title: "Physician Documentation Burden", date: "Feb 24, 2026", description: "Physicians spend 2–3 hours per day on EHR and paperwork instead of patients, driving burnout. Estimated cost to the US healthcare system: $150–250B/yr; current spend on documentation tools and scribes is $15–20B.", href: "/reports/market-opportunity-research/hc_01_physician_documentation_burden" },
  { slug: "hc_02_prior_authorization", title: "Prior Authorization Administrative Overload", date: "Feb 24, 2026", description: "Payers and providers spend ~$35–45B/year on prior-auth admin; practices devote ~14 hrs/week to PA. ePA and automation market is $2–2.5B and growing 11–13%, with CMS mandating electronic PA by 2027.", href: "/reports/market-opportunity-research/hc_02_prior_authorization" },
  { slug: "hc_03_clinical_trial_recruitment", title: "Clinical Trial Patient Recruitment Failure", date: "Feb 23, 2026", description: "80% of clinical trials are delayed by poor patient recruitment; sponsors lose ~$8M/day per delayed trial. Industry spends $15–20B on recruitment services and tech; total cost of recruitment failure is $30–50B/year.", href: "/reports/market-opportunity-research/hc_03_clinical_trial_recruitment" },
  { slug: "hc_04_pathology_backlog", title: "Pathology Lab Backlog", date: "Feb 22, 2026", description: "Multi-week backlogs delay cancer diagnoses due to pathologist shortage and manual slide reading. Economic cost of delayed diagnosis and shortage is $50–100B+/yr; digital/AI pathology is the fastest-growing segment.", href: "/reports/market-opportunity-research/hc_04_pathology_backlog" },
  { slug: "hc_04_pathology_lab_backlog", title: "Pathology Lab Backlog (report)", date: "Feb 21, 2026", description: "Pathology labs face severe backlogs and pathologist shortage, delaying cancer diagnoses. Report quantifies $50–100B+ annual cost and digital pathology market growth.", href: "/reports/market-opportunity-research/hc_04_pathology_lab_backlog" },
  { slug: "hc_05_claim_denials", title: "Insurance Claim Denial Management", date: "Feb 20, 2026", description: "15–25% of hospital claims are denied; $262B initially denied and $38–65B ultimately lost yearly. Denial management costs hospitals ~$19.7B; RCM market is $155–165B.", href: "/reports/market-opportunity-research/hc_05_claim_denials" },
  { slug: "hc_05_insurance_claim_denial_management", title: "Insurance Claim Denial Management (report)", date: "Feb 20, 2026", description: "Hospitals lose $38–65B/year to unrecovered denials and spend $19.7B on denial management. Report sizes the problem and the RCM/denial software market.", href: "/reports/market-opportunity-research/hc_05_insurance_claim_denial_management" },
  { slug: "hc_06_pharma_regulatory", title: "Regulatory Submission Assembly for Drug Approvals", date: "Feb 19, 2026", description: "Pharma spends years manually compiling FDA/EMA dossiers; $5–20M per NDA/BLA submission. Regulatory affairs spend is ~$12–15B/year; RIM software market is $3.2–4B.", href: "/reports/market-opportunity-research/hc_06_pharma_regulatory" },
  { slug: "hc_06_regulatory_submission_assembly", title: "Regulatory Submission Assembly", date: "Feb 18, 2026", description: "Manual assembly of regulatory dossiers costs $5–20M per submission and delays market entry by months. Report covers global regulatory spend and RIM market.", href: "/reports/market-opportunity-research/hc_06_regulatory_submission_assembly" },
  { slug: "hc_07_hospital_supply_waste", title: "Hospital Medical Supply Waste & Inventory Mismanagement", date: "Feb 17, 2026", description: "Hospital supply waste and inventory inefficiency cost $25–60B/year (expired stock, overordering, rush premiums). SCM software and GPO market is $3.3–3.6B globally.", href: "/reports/market-opportunity-research/hc_07_hospital_supply_waste" },
  { slug: "hc_08_preventable_hospital_readmissions", title: "Preventable Hospital Readmissions", date: "Feb 17, 2026", description: "~$26B/yr in preventable 30-day readmissions (Medicare); hospitals face HRRP penalties. Care management and transition software market is ~$16B and growing 12%+.", href: "/reports/market-opportunity-research/hc_08_preventable_hospital_readmissions" },
  { slug: "hc_08_readmissions", title: "Preventable Hospital Readmissions (report)", date: "Feb 16, 2026", description: "Preventable readmissions cost ~$13–17B (Medicare) to $41–52B (all payers) yearly. Report sizes the problem and care management software opportunity.", href: "/reports/market-opportunity-research/hc_08_readmissions" },
  { slug: "hosp_01_hotel_revenue", title: "Revenue Leakage at Independent Hotels from Manual Pricing", date: "Feb 15, 2026", description: "Independent hotels price manually and leave 20–30% revenue on the table vs chains. Revenue leakage from suboptimal pricing is estimated $42–84B/yr globally.", href: "/reports/market-opportunity-research/hosp_01_hotel_revenue" },
  { slug: "hosp_01_revenue_leakage_independent_hotels", title: "Revenue Leakage at Independent Hotels", date: "Feb 14, 2026", description: "Manual pricing at independent hotels creates a 20–35% RevPAR gap vs branded hotels. Global revenue leakage from this gap is $42–84B/year.", href: "/reports/market-opportunity-research/hosp_01_revenue_leakage_independent_hotels" },
  { slug: "hosp_02_group_mice_rfp_response_failure", title: "Group/MICE RFP Response Failure", date: "Feb 14, 2026", description: "50–70% of group/MICE RFPs go unanswered or delayed; revenue leakage from non-response is $100–150B+ globally. Report sizes the MICE market and response automation opportunity.", href: "/reports/market-opportunity-research/hosp_02_group_mice_rfp_response_failure" },
  { slug: "hosp_02_mice_rfp", title: "Group/MICE RFP Response Failure (report)", date: "Feb 13, 2026", description: "Hotels lose group business because many RFPs are never answered or are answered too slowly. Report quantifies $100–150B+ in lost revenue and the meetings tech market.", href: "/reports/market-opportunity-research/hosp_02_mice_rfp" },
  { slug: "hosp_03_food_waste", title: "F&B Food Waste from Poor Demand Forecasting", date: "Feb 12, 2026", description: "Poor demand forecasting in F&B causes 30–40% of purchased food to be wasted; net loss to operators is $100–150B globally. Hotel F&B and foodservice waste is $100–120B of that.", href: "/reports/market-opportunity-research/hosp_03_food_waste" },
  { slug: "hosp_04_ota_commissions", title: "OTA Commission Dependency & Rate Parity Management", date: "Feb 11, 2026", description: "Hotels pay $65–80B/year in OTA commissions (15–25% per booking); rate parity and discovery are controlled by OTAs. Channel management software is $500M–1B and growing 10–14%.", href: "/reports/market-opportunity-research/hosp_04_ota_commissions" },
  { slug: "hosp_05_guest_complaints", title: "Reactive Guest Complaint Management", date: "Feb 11, 2026", description: "Complaints surface on TripAdvisor/Google before staff respond; negative reviews put $130–150B in revenue at risk. Reputation and feedback tools are a growing segment.", href: "/reports/market-opportunity-research/hosp_05_guest_complaints" },
  { slug: "mfg_01_equipment_downtime", title: "Unplanned Equipment Downtime in Manufacturing", date: "Feb 10, 2026", description: "Unplanned downtime costs manufacturing $50B+/year globally; auto OEMs lose $1.3–2M/hour. Predictive maintenance and IIoT market is growing fast.", href: "/reports/market-opportunity-research/mfg_01_equipment_downtime" },
  { slug: "mfg_01_unplanned_equipment_downtime", title: "Unplanned Equipment Downtime (report)", date: "Feb 9, 2026", description: "Unplanned equipment downtime costs $50–100B+ annually in manufacturing. Report sizes the problem and the predictive maintenance / IIoT market.", href: "/reports/market-opportunity-research/mfg_01_unplanned_equipment_downtime" },
  { slug: "mfg_02_manual_visual_quality_control", title: "Manual Visual Quality Control on Production Lines", date: "Feb 8, 2026", description: "Manual visual inspection is inconsistent and misses defects; recalls and cost of poor quality run $10B+/yr (US). Machine vision market is ~$13–14B and growing 10–11%.", href: "/reports/market-opportunity-research/mfg_02_manual_visual_quality_control" },
  { slug: "mfg_02_visual_qc", title: "Manual Visual Quality Control", date: "Feb 7, 2026", description: "Manual visual QC on production lines drives recalls and rework. Report covers cost of poor quality and the industrial machine vision opportunity.", href: "/reports/market-opportunity-research/mfg_02_visual_qc" },
  { slug: "mfg_03_production_scheduling", title: "Production Scheduling Chaos in Discrete Manufacturing", date: "Feb 7, 2026", description: "Poor production scheduling causes $150–200B/year in excess inventory, late delivery penalties, and overtime. APS and MES scheduling modules are $2–5B and growing 11–14%.", href: "/reports/market-opportunity-research/mfg_03_production_scheduling" },
  { slug: "mfg_03_production_scheduling_chaos", title: "Production Scheduling Chaos (report)", date: "Feb 6, 2026", description: "Discrete manufacturing loses $150–200B+ yearly to scheduling chaos (inventory, penalties, lost orders). Report sizes APS/MES spend and the automation gap.", href: "/reports/market-opportunity-research/mfg_03_production_scheduling_chaos" },
  { slug: "mfg_04_ap_3way_match", title: "Manual AP 3-Way Match Exceptions in Industrial Procurement", date: "Feb 6, 2026", description: "AP teams spend 60%+ of time on PO/invoice/receipt exceptions; manual matching costs $170–250B globally. AP automation and e-invoicing are growing with regulatory mandates.", href: "/reports/market-opportunity-research/mfg_04_ap_3way_match" },
  { slug: "mfg_04_ap_match", title: "Manual AP 3-Way Match Exceptions", date: "Feb 5, 2026", description: "3-way match exceptions are resolved manually in industrial procurement; exception handling dominates AP labor. Report quantifies $170–250B in AP inefficiency and automation market.", href: "/reports/market-opportunity-research/mfg_04_ap_match" },
  { slug: "mfg_05_compliance_docs", title: "Compliance Documentation Assembly Burden", date: "Feb 4, 2026", description: "Manufacturers spend millions assembling ISO/FDA/CE compliance docs; audit prep takes months. Total compliance cost is $180–250B+; QMS and document management are $10–12B and $7–8B.", href: "/reports/market-opportunity-research/mfg_05_compliance_docs" },
  { slug: "mfg_05_compliance_documentation_assembly", title: "Compliance Documentation Assembly in Manufacturing", date: "Feb 4, 2026", description: "Manual assembly of compliance documentation for audits costs $250K–$2M per facility yearly. Report covers $180–250B+ total compliance cost and QMS/DMS market.", href: "/reports/market-opportunity-research/mfg_05_compliance_documentation_assembly" },
  { slug: "mfg_06_rfq_processing", title: "Manual RFQ Processing from CAD/Engineering Drawings", date: "Feb 3, 2026", description: "Job shops manually read CAD drawings to quote; 60–70% of RFQs go unquoted, losing $20–30B in revenue. CPQ and manufacturing quoting software are $2.4–3.2B and growing 14–17%.", href: "/reports/market-opportunity-research/mfg_06_rfq_processing" },
  { slug: "mfg_07_energy_waste", title: "Untracked Energy Waste in Manufacturing Plants", date: "Feb 2, 2026", description: "20–30% of industrial energy is wasted due to lack of monitoring; US manufacturers waste $50–70B/year. Global addressable waste is $420–750B; energy management software is growing.", href: "/reports/market-opportunity-research/mfg_07_energy_waste" },
] as const;

export type SubResearchSlug = (typeof MARKET_OPPORTUNITY_SUB_RESEARCHES)[number]["slug"];

export function getSubResearchBySlug(slug: string) {
  return MARKET_OPPORTUNITY_SUB_RESEARCHES.find((s) => s.slug === slug) ?? null;
}
